Quck project showing unserstanding of flexbox and other css concepts. 

Section one is a navbar with a h1 and a tags, below that is a h1/h2 
tag with a <p> and a button. to the right will be a image

Section two needs to contain an h2 tags and basiclly a row
of flexbox demonstrated images.

Section three is literally just a quote with some styling 

Section four is a footer with a button and some text 